django_core/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('detail/<int:pk>', views.detail, name='detail'),
    path('insert/', views.insert, name='insert'),

]

django_core/django_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("authors/", include("authors.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_core/quotes/urls.py
from django.urls import path, include
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="root_paginate"),
    path("insert/", views.insert, name="insert"),
    path("find/<tag_name>", views.find, name="find"),
]

django_core/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

django_core/quotes/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField(unique=True)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}"

django_core/quotes/forms.py
from django.forms import ModelForm, TextInput, CharField, ModelChoiceField, ModelMultipleChoiceField, \
    CheckboxSelectMultiple, SelectMultiple
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(max_length=250, required=True, widget=TextInput(attrs={"class": "form-control", "id": "exampleInputText1"}))
    author = ModelChoiceField(queryset=Author.objects.all(), empty_label="choose author...")
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False, widget=SelectMultiple)

    class Meta:
        model = Quote
        fields = ['quote', "author", "tags"]

django_core/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import QuoteForm
from .models import Author, Quote, Tag
from .utils import get_mongodb
from django.core.paginator import Paginator
from collections import Counter


def main(request, page=1):
    quotes = list(Quote.objects.all())
    paginator = Paginator(list(quotes), 10)
    quotes_on_page = paginator.page(page)
    top_ten = top_tags()
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, "top_tags": top_ten})


@login_required(login_url='quotes:main')
def insert(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'noteapp/note.html', {'form': form})
    return render(request, 'quotes/update.html', {"form": QuoteForm()})


def find(request, tag_name):
    quotes = list(Quote.objects.filter(tags__name=tag_name).all())
    return render(request, "quotes/tags.html", context={"result": tag_name, "quotes": quotes})


def top_tags():
    list_tags = []
    list_objects_tags = []
    for quote in list(Quote.objects.all()):
        for tag in list(quote.tags.all()):
            list_tags.append(tag.name)
    counter = Counter(list_tags)
    top_ten = list(sorted(counter, key=lambda x: counter[x], reverse=True)[:10])
    for tag in top_ten:
        list_objects_tags.append(Tag.objects.filter(name=tag).get())
    return list_objects_tags

django_core/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>DjangoApplication</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<div class="container mb-3">
    <div class="row header-box pt-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                <a href="{% url 'users:signup' %}" class="btn btn-primary">Signup</a>
                {% else %}
                <a href="{% url 'quotes:insert' %}" class="btn btn-success">Add Quote</a>
                <a href="{% url 'authors:insert' %}" class="btn btn-secondary">Add Author</a>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                {% endif %}
            </p>
        </div>
    </div>
    {% block content %} {% endblock %}
</div>
</body>
</html>

django_core/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}
{% load extract %}
{% block content %}
{% csrf_token %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            {% if quote.author %}
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="{% url 'authors:detail' quote.author.id %}"> (about)</a>
        {% endif %}
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find' tag.name%}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                {% if quotes.has_previous %}
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>
                {% endif %}
                {% if quotes.has_next %}
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <div class="col-md-3 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <p>
            <span class="tag-item">
                <a class="tag" href="{% url 'quotes:find' tag.name%}">{{tag.name}}</a>
            </span>
        </p>
        {% endfor %}
    </div>

</div>

{% endblock %}

django_core/quotes/templates/quotes/tags.html
{% extends "quotes/base.html" %}

{% block content %}
<h3>Results for tag: <i>{{result}}</i></h3>
<div class="row">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        {% if quote.author %}
        <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="{% url 'authors:detail' quote.author.id%}"> (about)</a>
        {% endif %}
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="{% url 'quotes:find' tag.name%}">{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

django_core/quotes/templates/quotes/update.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="row">
    <h2>Add Author</h2>
    <form method="POST" action="{% url 'quotes:insert' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputText1" class="form-label"> Quote</label>
            {{form.quote}}
            <span>{{form.errors.quote}}</span>
        </div>
        <div class="mb-3">
            <label for="exampleInputText2" class="form-label"> Author </label>
            {{form.author}}
            <span>{{form.errors.author}}</span>
        </div>
        <div class="mb-3">
            <div>Tags</div>
            <div>{{form.tags}}</div>
            <span>{{form.errors.tags}}</span>
        </div>

        </div>
        {% if messages %}
        <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-primary">Reset</button>
    </form>
</div>
{% endblock %}